package com.rikkabot.rikkabotcore.bot.middlewares;

import javax.xml.bind.DatatypeConverter;
import java.math.BigInteger;

/**
 * Encryption middleware.
 * ======================
 *
 * Serves as middleware between RikkaBot-core and TyrantsEye
 *
 * @author Manulaiko <manulaiko@gmail.com>
 */
public class EncryptionMiddleware {
    public static final BigInteger ENC_BASE_GENERATOR = new BigInteger(DatatypeConverter.parseHexBinary("5186a901d85d0ac6e757af306dc2b59d5f336ec4fdd470a5ac34e6654a85af15ead1c9e5b9ab856edca829c2bb8971eb4899a0d9b22de999965db56ba3d039a6"));
    public static final BigInteger ENC_PRIME_MODULUS = new BigInteger(DatatypeConverter.parseHexBinary("9c93fd6ec97b4e073afbb0580b1bbbd3f02e0c75a6c034fc405b03366f8ac3c2801b778a3f22b9f994fb7d57616cb9f70af488c19ea8da3d0ac613c2324e215b"));
    /**
     * Encryption key generated by the client
     */
    public static BigInteger privateKey;
    /**
     * Encrypts the output bytes.
     *
     * @param out Output bytes to encrypt.
     *
     * @return Encrypted byte array.
     */
    public static byte[] encrypt(byte[] out) {
        return out;
    }

    /**
     * Decrypts the input bytes.
     *
     * @param in Input bytes to decrypt.
     *
     * @return Decrypted byte array.
     */
    public static byte[] decrypt(byte[] in) {
        return in;
    }
}
